Repository REAN-Foundation/rean-bot-wrapper, pull requests merged in 2023-03, with the labels that each got.

#266 Bug/manasa random authentication issue
  src/api/controllers/client.webhook.controller.ts
Labels: bug

#268 Bug/manasa random authentication issue
  src/app.ts
  src/middleware/check.cross.connection.ts
Labels: bug

#274 Bug/manasa random authentication issue
  src/middleware/check.cross.connection.ts
  src/services/set.client/client.environment.provider.service.ts
Labels: bug, patch

#283 Updated for cross connection
  src/middleware/check.cross.connection.ts
Labels: patch

#284 Bug/whatsapp meta cross connection
  src/api/controllers/Frontend.Controller.ts
  src/api/controllers/client.webhook.controller.ts
  src/api/controllers/kobotoolbox.controller.ts
  src/api/routes/Frontend.routes.ts
  src/api/routes/chat.bot.routes.ts
  src/api/routes/platform.webhook.routes.ts
  src/api/routes/router.ts
  src/app.ts
  src/connection/sequelizeClient.ts
  src/intentEmitters/intentListeners/kerotoplasty.bot.condition.Identification.listener.ts
  src/intentEmitters/intentListeners/kerotoplasty.find.nearest.location.listener.ts
  src/intentEmitters/intentListeners/negative.feedabck.listener.ts
  src/middleware/check.cross.connection.ts
  src/services/app.support.service.ts
  src/services/aws.file.upload.service.ts
  src/services/calorie.service.ts
  src/services/clickup.message.service.ts
  src/services/clickup/clickup.task.ts
  src/services/clientAuthenticator/clickup.authenticator.ts
  src/services/clientAuthenticator/mockChannel.authenticator.ts
  src/services/clientAuthenticator/reanapp.authenticator.ts
  src/services/clientAuthenticator/slack.authenticator.servie.ts
  src/services/clientAuthenticator/sneha.authenticator.ts
  src/services/clientAuthenticator/telegram.authenticator.ts
  src/services/clientAuthenticator/whatsapp.authenticator.ts
  src/services/clientAuthenticator/whatsapp.meta.authenticator.ts
  src/services/custom.welcome.service.ts
  src/services/demoBot.service.ts
  src/services/dialogflow.response.service.ts
  src/services/feedback/feedback.service.ts
  src/services/filter.message.for.emoji.service.ts
  src/services/get.put.message.flow.service.ts
  src/services/handle.request.service.ts
  src/services/human.handoff.service.ts
  src/services/kerotoplasty.service.ts
  src/services/mock.channel.ts
  src/services/request.live.agent.service.ts
  src/services/response.format/dialogflow.response.format.ts
  src/services/set.client/client.environment.provider.service.ts
  src/services/slack.message.service.ts
  src/services/slackAndCkickupSendCustomMessage.ts
  src/services/sneha.support.service.ts
  src/services/speech.to.text.service.ts
  src/services/telegram.message.service.functionalities.ts
  src/services/telegram.message.service.ts
  src/services/telegram.messagetodialogflow.ts
  src/services/whatsapp.common.service.ts
  src/services/whatsapp.functionalities.ts
  src/services/whatsapp.message.service.ts
  src/services/whatsapp.meta.message.service.ts
  src/utils/elasticsearch.utility.ts
  src/utils/response.handler.ts
Labels: minor

#286 Bug/child container fix
  src/services/aws.file.upload.service.ts
  src/services/risk.assessment.info.service.ts
  src/services/telegram.message.service.functionalities.ts
  src/services/translate.service.ts
  src/services/whatsapp.functionalities.ts
  src/services/whatsapp.post.response.functionalities.ts
Labels: minor

#287 Bug/child container fix
  src/services/aws.file.upload.service.ts
  src/services/get.put.message.flow.service.ts
Labels: minor

#293 Bug/dependency container changes
  src/intentEmitters/intentListeners/anemia.bot.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/Verify.bridge.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/accept.donation.request.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/accept.volunteer.request.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/blood.bridge.status.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/change.tf.date.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/checklist.date.validation.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/donate.blood.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/donation.request.yes.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/donor.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/menu.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/new.userlistener.ts
  src/intentEmitters/intentListeners/bloodWarrior/patient.enroll.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/patient.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/raise.request.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/register.all.profile.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/reject.donor.request.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/schedule.donation.eligible.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/schedule.donation.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/schedule.donation.take.values.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/schedule.one.time.take.values.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/select.blood.group.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/volunteer.listener.ts
  src/intentEmitters/intentListeners/bloodWarrior/welcome.listener.ts
  src/intentEmitters/intentListeners/maternity.careplan.listener.ts
  src/services/app.support.service.ts
  src/services/bloodWrrior/accept.donation.request.service.ts
  src/services/bloodWrrior/accept.volunteer.request.service.ts
  src/services/bloodWrrior/blood.bridge.status.service.ts
  src/services/bloodWrrior/checklist.date.validation.service.ts
  src/services/bloodWrrior/chnage.transfusion.date.service.ts
  src/services/bloodWrrior/common.service.ts
  src/services/bloodWrrior/donate.blood.service.ts
  src/services/bloodWrrior/donation.request.yes.service.ts
  src/services/bloodWrrior/donor.service.ts
  src/services/bloodWrrior/menu.service.ts
  src/services/bloodWrrior/new.user.service.ts
  src/services/bloodWrrior/raise.request.service.ts
  src/services/bloodWrrior/register.all.profile.service.ts
  src/services/bloodWrrior/reject.donor.request.ts
  src/services/bloodWrrior/schedule.donation.elligible.service.ts
  src/services/bloodWrrior/schedule.donation.service.ts
  src/services/bloodWrrior/schedule.donationtake.values.service.ts
  src/services/bloodWrrior/schedule.one.time.take.values.service.ts
  src/services/bloodWrrior/select.blood.group.service.ts
  src/services/bloodWrrior/verify.bridge.service.ts
  src/services/bloodWrrior/volunteer.service.ts
  src/services/bloodWrrior/welcome.service.ts
  src/services/call.anemia.model.ts
  src/services/calorie.report.service.ts
  src/services/calorie.service.ts
  src/services/maternalCareplan/registration.service.ts
  src/services/needle.service.ts
  src/services/support.app.service.ts
Labels: patch
